version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_MULTIPLE_DATABASES: 'dev,test'
    volumes:
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
